// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

export const generateDescription = (descType: string, descCategory: string): string => {
  // take all descriptions from descriptionsLists
  const allDescriptions = descriptionsLists[descCategory]
  // get random description from allDescriptions
  const randomIndex = Math.floor(Math.random() * allDescriptions.length)
  const randomDescription = allDescriptions[randomIndex]
  return randomDescription
}

// Enum for platforms

// descriptions

const descriptionsLists = {
  funny: [
    'I think hidden underneath a lot of teachers are very sexy women.',
    "I like playing smart, savvy, sexy women -- because it's so not me!",
    'Woke up sexy as hell again…',
    'I let him taste it and now he’s a diabetic…',
    'Girls are like country roads, the best ones have CURVES!!!',
    'Can I borrow a kiss? I promise I’ll give it back.',
    'Oh, you like sleeping?… Me too! We should do it together sometime!',
    'Do you think I would look better in a skirt or tight jeans?',
    'I’m in my bed, you’re in yours. One of us is obviously in the wrong place.',
    'If you kiss my neck, then I am not responsible what happens next.',
    'You don’t have to be naked to be sexy.',
    'You’re in my inappropriate thoughts.',
    "Got the neighbors yellin' 'Earthquake!' when I make the bed shake…",
    "He call my Patty Cake 'cause the way that ass shakes…",
    'Last night you were in my room, and now my bedsheets smell like you…',
    "I'm your slave, I'll let you whip me if I misbehave…",
    "Let's put it into motion, I'mma give you a promotion, I'll make it feel like a vacay, turn the bed into an ocean.",
    "No chance that I'm leaving here without you on me…",
    'I wanna fuck you with the lights on, keep you up all night…',
    'I want you to see every inch of me, get lost in the way I move…',
    "You have a pocket full of horses… Trojans, let's use some of them…",
    'I wanna be on you. Make my ovaries explode…',
    'You must forgive my lips… they find pleasure in the most unusual places.',
    'I wear dresses to do it a favor!!!',
    'Nobody puts Baby in a corner.',
    'What do you say we blow this joint and then each other?',
    'Did anyone ever tell you that your lips belong in unholy places???',
    'Y’know, I could eat a peach for hours.',
    "It says you're too sexy to be smart, but not smart enough to be sexy.",
    "I don't condone this sexy yet reckless behavior ;)",
    "I've got a degree in ass wiggling.",
    "Don't think unnatural thoughts about me…",
    'You must never underestimate the power of the eyebrow.',
    'Whoa, smack that ass!',
    "Bubble, bubble! I'm in trouble!",
    "Look how I move! That's just like Jell-O on springs.",
    'Be sexy in business. Be successful at night.',
    'When I sit down to eat, I get sexy! When I go to bed, I get hungry!',
    'Are you a drill sergeant? Because you have my privates standing at attention.',
    'Do you like to draw? Because I put the D in Raw.',
    'Want to see if I can add “has an awesome gag reflex” to my resume?',
    'Do you want to commit a sin for your next confessional?',
    'The FBI wants to steal your penis. Want to hide it inside me?',
    'I’m not into watching sunsets, but I’d love to see you go down.',
    'If it’s true that we are what we eat, then I could be you by morning.',
    'Want to kiss my Beautiful Lips? And the one on my face too??',
    'Vacuum your lap, I need a clean place to sit…',
    'I lost my keys… Can I check your pants?',
    'I just came out of the oven. Was too cold in there!',
    'I’m wasted, but the condom in your pocket doesn’t have to be.',
    "You're a pain in my ass… We can just add more lubricant.",
    'I lost my virginity. Can I have yours?',
    'I’m on top of things.',
    'My bed is broken. Can I use yours?',
    'We should settle this with a tongue-wrestling match.',
    'Sorry if I seem a little distracted tonight. I’m just not really feeling myself. I’d much rather be feeling you.',
    'Let’s play Titanic. You be the iceberg, and I’ll be the ship. First, we’ll smash, and then I’ll go down.',
    'Here, flip this coin, then give me whatever comes up.',
    'I must be turning into a beaver because I can’t stop thinking about putting your wood in my mouth.',
    'I’ll let you make me breakfast in the morning.',
    'Pretend I’m your homework, spread me out on the table, and do me until you can’t see straight.',
    'That’s impressive. You a girl scout?',
    'You have to kiss a lot of frogs before you find your prince.',
    'Never trust a man who can dance.',
    'Even a pain in the ass needs someone to care about them.',
    'I used your toothbrush.',
    'Interviews seem like such artificial situations, everyone on their best behavior trying desperately to hide behind a professional facade. Did my face fit?',
    "I'm no longer screening what's coming out of my mouth.",
    "You wouldn't want to ruin your clothing. I could just take them off.",
    'I just want you to be happy.. and Naked!!',
    'Better to be the one who smiled than the one who didn’t smile back…',
    'If you have a bad day don’t take it out on me… unless we’re both naked…',
    'Get naked… I have a plan…',
    'Make me laugh, then make me moan…',
    'Don’t ask for sex. Pick me up and carry me to bed like a Viking!',
    'Old enough to know better, young enough to do it anyway.',
    "I'm sorry, I can't be good all the time. The naughty in me is just way too strong.",
    'We all deserve morning sex and pancakes.',
    "If you're going to be bad… invite me!",
    'If you obey all the rules you miss all the fun.'
  ],
  motivational: [
    'I think hidden underneath a lot of teachers are very sexy women.',
    "I like playing smart, savvy, sexy women -- because it's so not me!",
    'Woke up sexy as hell again…',
    'I let him taste it and now he’s a diabetic…',
    'Girls are like country roads, the best ones have CURVES!!!',
    'Can I borrow a kiss? I promise I’ll give it back.',
    'Oh, you like sleeping?… Me too! We should do it together sometime!',
    'Do you think I would look better in a skirt or tight jeans?',
    'I’m in my bed, you’re in yours. One of us is obviously in the wrong place.',
    'If you kiss my neck, then I am not responsible what happens next.',
    'You don’t have to be naked to be sexy.',
    'You’re in my inappropriate thoughts.',
    "Got the neighbors yellin' 'Earthquake!' when I make the bed shake…",
    "He call my Patty Cake 'cause the way that ass shakes…",
    'Last night you were in my room, and now my bedsheets smell like you…',
    "I'm your slave, I'll let you whip me if I misbehave…",
    "Let's put it into motion, I'mma give you a promotion, I'll make it feel like a vacay, turn the bed into an ocean.",
    "No chance that I'm leaving here without you on me…",
    'I wanna fuck you with the lights on, keep you up all night…',
    'I want you to see every inch of me, get lost in the way I move…',
    "You have a pocket full of horses… Trojans, let's use some of them…",
    'I wanna be on you. Make my ovaries explode…',
    'You must forgive my lips… they find pleasure in the most unusual places.',
    'I wear dresses to do it a favor!!!',
    'Nobody puts Baby in a corner.',
    'What do you say we blow this joint and then each other?',
    'Did anyone ever tell you that your lips belong in unholy places???',
    'Y’know, I could eat a peach for hours.',
    "It says you're too sexy to be smart, but not smart enough to be sexy.",
    "I don't condone this sexy yet reckless behavior ;)",
    "I've got a degree in ass wiggling.",
    "Don't think unnatural thoughts about me…",
    'You must never underestimate the power of the eyebrow.',
    'Whoa, smack that ass!',
    "Bubble, bubble! I'm in trouble!",
    "Look how I move! That's just like Jell-O on springs.",
    'Be sexy in business. Be successful at night.',
    'When I sit down to eat, I get sexy! When I go to bed, I get hungry!',
    'Are you a drill sergeant? Because you have my privates standing at attention.',
    'Do you like to draw? Because I put the D in Raw.',
    'Want to see if I can add “has an awesome gag reflex” to my resume?',
    'Do you want to commit a sin for your next confessional?',
    'The FBI wants to steal your penis. Want to hide it inside me?',
    'I’m not into watching sunsets, but I’d love to see you go down.',
    'If it’s true that we are what we eat, then I could be you by morning.',
    'Want to kiss my Beautiful Lips? And the one on my face too??',
    'Vacuum your lap, I need a clean place to sit…',
    'I lost my keys… Can I check your pants?',
    'I just came out of the oven. Was too cold in there!',
    'I’m wasted, but the condom in your pocket doesn’t have to be.',
    "You're a pain in my ass… We can just add more lubricant.",
    'I lost my virginity. Can I have yours?',
    'I’m on top of things.',
    'My bed is broken. Can I use yours?',
    'We should settle this with a tongue-wrestling match.',
    'Sorry if I seem a little distracted tonight. I’m just not really feeling myself. I’d much rather be feeling you.',
    'Let’s play Titanic. You be the iceberg, and I’ll be the ship. First, we’ll smash, and then I’ll go down.',
    'Here, flip this coin, then give me whatever comes up.',
    'I must be turning into a beaver because I can’t stop thinking about putting your wood in my mouth.',
    'I’ll let you make me breakfast in the morning.',
    'Pretend I’m your homework, spread me out on the table, and do me until you can’t see straight.',
    'That’s impressive. You a girl scout?',
    'You have to kiss a lot of frogs before you find your prince.',
    'Never trust a man who can dance.',
    'Even a pain in the ass needs someone to care about them.',
    'I used your toothbrush.',
    'Interviews seem like such artificial situations, everyone on their best behavior trying desperately to hide behind a professional facade. Did my face fit?',
    "I'm no longer screening what's coming out of my mouth.",
    "You wouldn't want to ruin your clothing. I could just take them off.",
    'I just want you to be happy.. and Naked!!',
    'Better to be the one who smiled than the one who didn’t smile back…',
    'If you have a bad day don’t take it out on me… unless we’re both naked…',
    'Get naked… I have a plan…',
    'Make me laugh, then make me moan…',
    'Don’t ask for sex. Pick me up and carry me to bed like a Viking!',
    'Old enough to know better, young enough to do it anyway.',
    "I'm sorry, I can't be good all the time. The naughty in me is just way too strong.",
    'We all deserve morning sex and pancakes.',
    "If you're going to be bad… invite me!",
    'If you obey all the rules you miss all the fun.'
  ],
  adult: [
    'I think hidden underneath a lot of teachers are very sexy women.',
    "I like playing smart, savvy, sexy women -- because it's so not me!",
    'Woke up sexy as hell again…',
    'I let him taste it and now he’s a diabetic…',
    'Girls are like country roads, the best ones have CURVES!!!',
    'Can I borrow a kiss? I promise I’ll give it back.',
    'Oh, you like sleeping?… Me too! We should do it together sometime!',
    'Do you think I would look better in a skirt or tight jeans?',
    'I’m in my bed, you’re in yours. One of us is obviously in the wrong place.',
    'If you kiss my neck, then I am not responsible what happens next.',
    'You don’t have to be naked to be sexy.',
    'You’re in my inappropriate thoughts.',
    "Got the neighbors yellin' 'Earthquake!' when I make the bed shake…",
    "He call my Patty Cake 'cause the way that ass shakes…",
    'Last night you were in my room, and now my bedsheets smell like you…',
    "I'm your slave, I'll let you whip me if I misbehave…",
    "Let's put it into motion, I'mma give you a promotion, I'll make it feel like a vacay, turn the bed into an ocean.",
    "No chance that I'm leaving here without you on me…",
    'I wanna fuck you with the lights on, keep you up all night…',
    'I want you to see every inch of me, get lost in the way I move…',
    "You have a pocket full of horses… Trojans, let's use some of them…",
    'I wanna be on you. Make my ovaries explode…',
    'You must forgive my lips… they find pleasure in the most unusual places.',
    'I wear dresses to do it a favor!!!',
    'Nobody puts Baby in a corner.',
    'What do you say we blow this joint and then each other?',
    'Did anyone ever tell you that your lips belong in unholy places???',
    'Y’know, I could eat a peach for hours.',
    "It says you're too sexy to be smart, but not smart enough to be sexy.",
    "I don't condone this sexy yet reckless behavior ;)",
    "I've got a degree in ass wiggling.",
    "Don't think unnatural thoughts about me…",
    'You must never underestimate the power of the eyebrow.',
    'Whoa, smack that ass!',
    "Bubble, bubble! I'm in trouble!",
    "Look how I move! That's just like Jell-O on springs.",
    'Be sexy in business. Be successful at night.',
    'When I sit down to eat, I get sexy! When I go to bed, I get hungry!',
    'Are you a drill sergeant? Because you have my privates standing at attention.',
    'Do you like to draw? Because I put the D in Raw.',
    'Want to see if I can add “has an awesome gag reflex” to my resume?',
    'Do you want to commit a sin for your next confessional?',
    'The FBI wants to steal your penis. Want to hide it inside me?',
    'I’m not into watching sunsets, but I’d love to see you go down.',
    'If it’s true that we are what we eat, then I could be you by morning.',
    'Want to kiss my Beautiful Lips? And the one on my face too??',
    'Vacuum your lap, I need a clean place to sit…',
    'I lost my keys… Can I check your pants?',
    'I just came out of the oven. Was too cold in there!',
    'I’m wasted, but the condom in your pocket doesn’t have to be.',
    "You're a pain in my ass… We can just add more lubricant.",
    'I lost my virginity. Can I have yours?',
    'I’m on top of things.',
    'My bed is broken. Can I use yours?',
    'We should settle this with a tongue-wrestling match.',
    'Sorry if I seem a little distracted tonight. I’m just not really feeling myself. I’d much rather be feeling you.',
    'Let’s play Titanic. You be the iceberg, and I’ll be the ship. First, we’ll smash, and then I’ll go down.',
    'Here, flip this coin, then give me whatever comes up.',
    'I must be turning into a beaver because I can’t stop thinking about putting your wood in my mouth.',
    'I’ll let you make me breakfast in the morning.',
    'Pretend I’m your homework, spread me out on the table, and do me until you can’t see straight.',
    'That’s impressive. You a girl scout?',
    'You have to kiss a lot of frogs before you find your prince.',
    'Never trust a man who can dance.',
    'Even a pain in the ass needs someone to care about them.',
    'I used your toothbrush.',
    'Interviews seem like such artificial situations, everyone on their best behavior trying desperately to hide behind a professional facade. Did my face fit?',
    "I'm no longer screening what's coming out of my mouth.",
    "You wouldn't want to ruin your clothing. I could just take them off.",
    'I just want you to be happy.. and Naked!!',
    'Better to be the one who smiled than the one who didn’t smile back…',
    'If you have a bad day don’t take it out on me… unless we’re both naked…',
    'Get naked… I have a plan…',
    'Make me laugh, then make me moan…',
    'Don’t ask for sex. Pick me up and carry me to bed like a Viking!',
    'Old enough to know better, young enough to do it anyway.',
    "I'm sorry, I can't be good all the time. The naughty in me is just way too strong.",
    'We all deserve morning sex and pancakes.',
    "If you're going to be bad… invite me!",
    'If you obey all the rules you miss all the fun.'
  ],
  educational: [
    'I think hidden underneath a lot of teachers are very sexy women.',
    "I like playing smart, savvy, sexy women -- because it's so not me!",
    'Woke up sexy as hell again…',
    'I let him taste it and now he’s a diabetic…',
    'Girls are like country roads, the best ones have CURVES!!!',
    'Can I borrow a kiss? I promise I’ll give it back.',
    'Oh, you like sleeping?… Me too! We should do it together sometime!',
    'Do you think I would look better in a skirt or tight jeans?',
    'I’m in my bed, you’re in yours. One of us is obviously in the wrong place.',
    'If you kiss my neck, then I am not responsible what happens next.',
    'You don’t have to be naked to be sexy.',
    'You’re in my inappropriate thoughts.',
    "Got the neighbors yellin' 'Earthquake!' when I make the bed shake…",
    "He call my Patty Cake 'cause the way that ass shakes…",
    'Last night you were in my room, and now my bedsheets smell like you…',
    "I'm your slave, I'll let you whip me if I misbehave…",
    "Let's put it into motion, I'mma give you a promotion, I'll make it feel like a vacay, turn the bed into an ocean.",
    "No chance that I'm leaving here without you on me…",
    'I wanna fuck you with the lights on, keep you up all night…',
    'I want you to see every inch of me, get lost in the way I move…',
    "You have a pocket full of horses… Trojans, let's use some of them…",
    'I wanna be on you. Make my ovaries explode…',
    'You must forgive my lips… they find pleasure in the most unusual places.',
    'I wear dresses to do it a favor!!!',
    'Nobody puts Baby in a corner.',
    'What do you say we blow this joint and then each other?',
    'Did anyone ever tell you that your lips belong in unholy places???',
    'Y’know, I could eat a peach for hours.',
    "It says you're too sexy to be smart, but not smart enough to be sexy.",
    "I don't condone this sexy yet reckless behavior ;)",
    "I've got a degree in ass wiggling.",
    "Don't think unnatural thoughts about me…",
    'You must never underestimate the power of the eyebrow.',
    'Whoa, smack that ass!',
    "Bubble, bubble! I'm in trouble!",
    "Look how I move! That's just like Jell-O on springs.",
    'Be sexy in business. Be successful at night.',
    'When I sit down to eat, I get sexy! When I go to bed, I get hungry!',
    'Are you a drill sergeant? Because you have my privates standing at attention.',
    'Do you like to draw? Because I put the D in Raw.',
    'Want to see if I can add “has an awesome gag reflex” to my resume?',
    'Do you want to commit a sin for your next confessional?',
    'The FBI wants to steal your penis. Want to hide it inside me?',
    'I’m not into watching sunsets, but I’d love to see you go down.',
    'If it’s true that we are what we eat, then I could be you by morning.',
    'Want to kiss my Beautiful Lips? And the one on my face too??',
    'Vacuum your lap, I need a clean place to sit…',
    'I lost my keys… Can I check your pants?',
    'I just came out of the oven. Was too cold in there!',
    'I’m wasted, but the condom in your pocket doesn’t have to be.',
    "You're a pain in my ass… We can just add more lubricant.",
    'I lost my virginity. Can I have yours?',
    'I’m on top of things.',
    'My bed is broken. Can I use yours?',
    'We should settle this with a tongue-wrestling match.',
    'Sorry if I seem a little distracted tonight. I’m just not really feeling myself. I’d much rather be feeling you.',
    'Let’s play Titanic. You be the iceberg, and I’ll be the ship. First, we’ll smash, and then I’ll go down.',
    'Here, flip this coin, then give me whatever comes up.',
    'I must be turning into a beaver because I can’t stop thinking about putting your wood in my mouth.',
    'I’ll let you make me breakfast in the morning.',
    'Pretend I’m your homework, spread me out on the table, and do me until you can’t see straight.',
    'That’s impressive. You a girl scout?',
    'You have to kiss a lot of frogs before you find your prince.',
    'Never trust a man who can dance.',
    'Even a pain in the ass needs someone to care about them.',
    'I used your toothbrush.',
    'Interviews seem like such artificial situations, everyone on their best behavior trying desperately to hide behind a professional facade. Did my face fit?',
    "I'm no longer screening what's coming out of my mouth.",
    "You wouldn't want to ruin your clothing. I could just take them off.",
    'I just want you to be happy.. and Naked!!',
    'Better to be the one who smiled than the one who didn’t smile back…',
    'If you have a bad day don’t take it out on me… unless we’re both naked…',
    'Get naked… I have a plan…',
    'Make me laugh, then make me moan…',
    'Don’t ask for sex. Pick me up and carry me to bed like a Viking!',
    'Old enough to know better, young enough to do it anyway.',
    "I'm sorry, I can't be good all the time. The naughty in me is just way too strong.",
    'We all deserve morning sex and pancakes.',
    "If you're going to be bad… invite me!",
    'If you obey all the rules you miss all the fun.'
  ]
}

export default descriptionsLists
